// <auto-generated />
using System;
using CozaStoreAPI.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CozaStoreAPI.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240926172557_01")]
    partial class _01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CozaStoreAPI.Infrastructure.Data.Models.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("First Name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Last Name");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("ShippingCity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("User's shipping city");

                    b.Property<string>("ShippingOffice")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("User's shipping office");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f415401c-db9c-4e89-bf5f-d75b7e1301fc"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e00cde30-23dd-4d56-b6f7-2e551a6c02d1",
                            Email = "test@test.com",
                            EmailConfirmed = true,
                            FirstName = "TestFirstName",
                            LastName = "TestLastName",
                            LockoutEnabled = false,
                            NormalizedEmail = "TEST@TEST.COM",
                            NormalizedUserName = "TEST@TEST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIDV5z3uIpqH0mMSfGi6kA/r+myic+aN4lgo2MfqgLTrcQsA5TBzVMSxjDRRY6WitQ==",
                            PhoneNumber = "0888 888 888",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "NNC2KI3MK4ONPNJIS5HUOKHN3565MBID",
                            ShippingCity = "",
                            ShippingOffice = "",
                            TwoFactorEnabled = false,
                            UserName = "test@test.com"
                        });
                });

            modelBuilder.Entity("CozaStoreAPI.Infrastructure.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("The category's primary key");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("The category's name");

                    b.HasKey("Id");

                    b.ToTable("Categories", t =>
                        {
                            t.HasComment("The category of the product");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "women"
                        },
                        new
                        {
                            Id = 2,
                            Name = "man"
                        },
                        new
                        {
                            Id = 3,
                            Name = "shoes"
                        },
                        new
                        {
                            Id = 4,
                            Name = "watches"
                        },
                        new
                        {
                            Id = 5,
                            Name = "bag"
                        });
                });

            modelBuilder.Entity("CozaStoreAPI.Infrastructure.Data.Models.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("The color's primary key");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("The color's name");

                    b.HasKey("Id");

                    b.ToTable("Colors", t =>
                        {
                            t.HasComment("The color of the product");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "White"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Black"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Red"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Green"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Blue"
                        });
                });

            modelBuilder.Entity("CozaStoreAPI.Infrastructure.Data.Models.EcontCity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasComment("Shipping city Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Name of shipping city");

                    b.HasKey("Id");

                    b.ToTable("EcontCities", t =>
                        {
                            t.HasComment("Table of shipping cities");
                        });
                });

            modelBuilder.Entity("CozaStoreAPI.Infrastructure.Data.Models.EcontOffice", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasComment("Shipping office Id");

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasComment("Name of office city");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("EcontOffices", t =>
                        {
                            t.HasComment("Table of shipping cities");
                        });
                });

            modelBuilder.Entity("CozaStoreAPI.Infrastructure.Data.Models.ImageProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("The image id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ImageOrder")
                        .HasColumnType("integer")
                        .HasComment("The image's order in slider");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasComment("The path of the image");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ImageProducts", t =>
                        {
                            t.HasComment("The image of the product");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageOrder = 1,
                            ImagePath = "/images/product-01.jpg",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            ImageOrder = 2,
                            ImagePath = "/images/product-02.jpg",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 3,
                            ImageOrder = 1,
                            ImagePath = "/images/product-02.jpg",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 4,
                            ImageOrder = 1,
                            ImagePath = "/images/product-03.jpg",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 5,
                            ImageOrder = 1,
                            ImagePath = "/images/product-04.jpg",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 6,
                            ImageOrder = 1,
                            ImagePath = "/images/product-05.jpg",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 7,
                            ImageOrder = 1,
                            ImagePath = "/images/product-06.jpg",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 8,
                            ImageOrder = 1,
                            ImagePath = "/images/product-07.jpg",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 9,
                            ImageOrder = 1,
                            ImagePath = "/images/product-08.jpg",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 10,
                            ImageOrder = 1,
                            ImagePath = "/images/product-09.jpg",
                            ProductId = 9
                        },
                        new
                        {
                            Id = 11,
                            ImageOrder = 1,
                            ImagePath = "/images/product-10.jpg",
                            ProductId = 10
                        },
                        new
                        {
                            Id = 12,
                            ImageOrder = 1,
                            ImagePath = "/images/product-11.jpg",
                            ProductId = 11
                        },
                        new
                        {
                            Id = 13,
                            ImageOrder = 1,
                            ImagePath = "/images/product-12.jpg",
                            ProductId = 12
                        },
                        new
                        {
                            Id = 14,
                            ImageOrder = 1,
                            ImagePath = "/images/product-13.jpg",
                            ProductId = 13
                        },
                        new
                        {
                            Id = 15,
                            ImageOrder = 1,
                            ImagePath = "/images/product-14.jpg",
                            ProductId = 14
                        },
                        new
                        {
                            Id = 16,
                            ImageOrder = 1,
                            ImagePath = "/images/product-15.jpg",
                            ProductId = 15
                        },
                        new
                        {
                            Id = 17,
                            ImageOrder = 1,
                            ImagePath = "/images/product-16.jpg",
                            ProductId = 16
                        });
                });

            modelBuilder.Entity("CozaStoreAPI.Infrastructure.Data.Models.ImageReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("The image id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasComment("The path of the image");

                    b.Property<int>("ReviewId")
                        .HasColumnType("integer")
                        .HasComment("The review id");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId");

                    b.ToTable("ImageReviews", t =>
                        {
                            t.HasComment("The image of the review");
                        });
                });

            modelBuilder.Entity("CozaStoreAPI.Infrastructure.Data.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Primary key");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasComment("Content of the message");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Email of the user");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("First name of the user");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Last name of the user");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Subject of the message");

                    b.HasKey("Id");

                    b.ToTable("Messages", t =>
                        {
                            t.HasComment("Table of messages from users");
                        });
                });

            modelBuilder.Entity("CozaStoreAPI.Infrastructure.Data.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Order Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uuid")
                        .HasComment("App User Id");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date of Order Creating");

                    b.Property<DateTimeOffset?>("DateShipping")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date of Shipping Creating");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("First Name Recipient");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean")
                        .HasComment("Is Paid Order");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Last Name Recipient");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Order Number");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasComment("Phone Number Recipient");

                    b.Property<string>("ShippingCity")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("City Recipient");

                    b.Property<string>("ShippingOffice")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasComment("Office Recipient");

                    b.Property<decimal>("ShippingPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Shipping Price");

                    b.Property<string>("ShippingProvider")
                        .HasColumnType("text")
                        .HasComment("Shipping Provider");

                    b.Property<int>("StatusOrderId")
                        .HasColumnType("integer")
                        .HasComment("Status of Order");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Total Price");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasComment("Tracking Number of Order");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("StatusOrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CozaStoreAPI.Infrastructure.Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("The product's primary key");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer")
                        .HasComment("The product's category id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("The product's created date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasComment("The product's description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("The product is deleted or not");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("The product's material");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("The product's name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("The product's price");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("The product's updated date");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", t =>
                        {
                            t.HasComment("The product");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 26, 20, 25, 56, 631, DateTimeKind.Unspecified).AddTicks(6660), new TimeSpan(0, 3, 0, 0, 0)),
                            Description = "Description of product Esprit Ruffle Shirt",
                            IsDeleted = false,
                            Material = "60% cotton, 40% polyester",
                            Name = "Esprit Ruffle Shirt",
                            Price = 16.64m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 26, 20, 25, 56, 631, DateTimeKind.Unspecified).AddTicks(6721), new TimeSpan(0, 3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 26, 20, 25, 56, 631, DateTimeKind.Unspecified).AddTicks(6726), new TimeSpan(0, 3, 0, 0, 0)),
                            Description = "Description of product Herschel supply",
                            IsDeleted = false,
                            Material = "60% cotton, 40% polyester",
                            Name = "Herschel supply",
                            Price = 35.31m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 26, 20, 25, 56, 631, DateTimeKind.Unspecified).AddTicks(6728), new TimeSpan(0, 3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 26, 20, 25, 56, 631, DateTimeKind.Unspecified).AddTicks(6733), new TimeSpan(0, 3, 0, 0, 0)),
                            Description = "Description of product Only Check Trouser",
                            IsDeleted = false,
                            Material = "60% cotton, 40% polyester",
                            Name = "Only Check Trouser",
                            Price = 25.50m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 26, 20, 25, 56, 631, DateTimeKind.Unspecified).AddTicks(6735), new TimeSpan(0, 3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 26, 20, 25, 56, 631, DateTimeKind.Unspecified).AddTicks(6739), new TimeSpan(0, 3, 0, 0, 0)),
                            Description = "Description of product Classic Trench Coat",
                            IsDeleted = false,
                            Material = "60% cotton, 40% polyester",
                            Name = "Classic Trench Coat",
                            Price = 75.00m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 26, 20, 25, 56, 631, DateTimeKind.Unspecified).AddTicks(6741), new TimeSpan(0, 3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 26, 20, 25, 56, 631, DateTimeKind.Unspecified).AddTicks(6746), new TimeSpan(0, 3, 0, 0, 0)),
                            Description = "Description of product Front Pocket Jumper",
                            IsDeleted = false,
                            Material = "60% cotton, 40% polyester",
                            Name = "Front Pocket Jumper",
                            Price = 34.75m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 26, 20, 25, 56, 631, DateTimeKind.Unspecified).AddTicks(6748), new TimeSpan(0, 3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 26, 20, 25, 56, 631, DateTimeKind.Unspecified).AddTicks(6753), new TimeSpan(0, 3, 0, 0, 0)),
                            Description = "Description of product Vintage Inspired Classic",
                            IsDeleted = false,
                            Material = "",
                            Name = "Vintage Inspired Classic",
                            Price = 93.20m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 26, 20, 25, 56, 631, DateTimeKind.Unspecified).AddTicks(6755), new TimeSpan(0, 3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 26, 20, 25, 56, 631, DateTimeKind.Unspecified).AddTicks(6759), new TimeSpan(0, 3, 0, 0, 0)),
                            Description = "Description of product Shirt in Stretch Cotton",
                            IsDeleted = false,
                            Material = "60% cotton, 40% polyester",
                            Name = "Shirt in Stretch Cotton",
                            Price = 52.66m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 26, 20, 25, 56, 631, DateTimeKind.Unspecified).AddTicks(6761), new TimeSpan(0, 3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 26, 20, 25, 56, 631, DateTimeKind.Unspecified).AddTicks(6832), new TimeSpan(0, 3, 0, 0, 0)),
                            Description = "Description of product Pieces Metallic Printed",
                            IsDeleted = false,
                            Material = "60% cotton, 40% polyester",
                            Name = "Pieces Metallic Printed",
                            Price = 18.96m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 26, 20, 25, 56, 631, DateTimeKind.Unspecified).AddTicks(6834), new TimeSpan(0, 3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 26, 20, 25, 56, 631, DateTimeKind.Unspecified).AddTicks(6839), new TimeSpan(0, 3, 0, 0, 0)),
                            Description = "Description of product Converse All Star Hi Plimsolls",
                            IsDeleted = false,
                            Material = "60% cotton, 40% polyester",
                            Name = "Converse All Star Hi Plimsolls",
                            Price = 75.00m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 26, 20, 25, 56, 631, DateTimeKind.Unspecified).AddTicks(6841), new TimeSpan(0, 3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 26, 20, 25, 56, 631, DateTimeKind.Unspecified).AddTicks(6845), new TimeSpan(0, 3, 0, 0, 0)),
                            Description = "Description of product Femme T-Shirt In Stripe",
                            IsDeleted = false,
                            Material = "60% cotton, 40% polyester",
                            Name = "Femme T-Shirt In Stripe",
                            Price = 25.85m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 26, 20, 25, 56, 631, DateTimeKind.Unspecified).AddTicks(6847), new TimeSpan(0, 3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 26, 20, 25, 56, 631, DateTimeKind.Unspecified).AddTicks(6851), new TimeSpan(0, 3, 0, 0, 0)),
                            Description = "Description of product Herschel supply",
                            IsDeleted = false,
                            Material = "60% cotton, 40% polyester",
                            Name = "Herschel supply",
                            Price = 63.16m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 26, 20, 25, 56, 631, DateTimeKind.Unspecified).AddTicks(6853), new TimeSpan(0, 3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 26, 20, 25, 56, 631, DateTimeKind.Unspecified).AddTicks(6857), new TimeSpan(0, 3, 0, 0, 0)),
                            Description = "Description of product Herschel supply",
                            IsDeleted = false,
                            Material = "100% leather",
                            Name = "Herschel supply",
                            Price = 63.15m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 26, 20, 25, 56, 631, DateTimeKind.Unspecified).AddTicks(6859), new TimeSpan(0, 3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 26, 20, 25, 56, 631, DateTimeKind.Unspecified).AddTicks(6863), new TimeSpan(0, 3, 0, 0, 0)),
                            Description = "Description of product T-Shirt with Sleeve",
                            IsDeleted = false,
                            Material = "60% cotton, 40% polyester",
                            Name = "T-Shirt with Sleeve",
                            Price = 18.49m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 26, 20, 25, 56, 631, DateTimeKind.Unspecified).AddTicks(6865), new TimeSpan(0, 3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 26, 20, 25, 56, 631, DateTimeKind.Unspecified).AddTicks(6869), new TimeSpan(0, 3, 0, 0, 0)),
                            Description = "Description of product Pretty Little Thing",
                            IsDeleted = false,
                            Material = "60% cotton, 40% polyester",
                            Name = "Pretty Little Thing",
                            Price = 54.79m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 26, 20, 25, 56, 631, DateTimeKind.Unspecified).AddTicks(6871), new TimeSpan(0, 3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 26, 20, 25, 56, 631, DateTimeKind.Unspecified).AddTicks(6875), new TimeSpan(0, 3, 0, 0, 0)),
                            Description = "Description of product Mini Silver Mesh Watch",
                            IsDeleted = false,
                            Material = "",
                            Name = "Mini Silver Mesh Watch",
                            Price = 86.85m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 26, 20, 25, 56, 631, DateTimeKind.Unspecified).AddTicks(6877), new TimeSpan(0, 3, 0, 0, 0))
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 9, 26, 20, 25, 56, 631, DateTimeKind.Unspecified).AddTicks(6881), new TimeSpan(0, 3, 0, 0, 0)),
                            Description = "Description of product Square Neck Back",
                            IsDeleted = false,
                            Material = "60% cotton, 40% polyester",
                            Name = "Square Neck Back",
                            Price = 29.64m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 9, 26, 20, 25, 56, 631, DateTimeKind.Unspecified).AddTicks(6883), new TimeSpan(0, 3, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("CozaStoreAPI.Infrastructure.Data.Models.ProductColor", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasComment("The product's id");

                    b.Property<int>("ColorId")
                        .HasColumnType("integer")
                        .HasComment("The size's id");

                    b.HasKey("ProductId", "ColorId");

                    b.HasIndex("ColorId");

                    b.ToTable("ProductsColors", t =>
                        {
                            t.HasComment("Many to many relation between products and colors");
                        });

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            ColorId = 1
                        },
                        new
                        {
                            ProductId = 1,
                            ColorId = 2
                        },
                        new
                        {
                            ProductId = 1,
                            ColorId = 3
                        },
                        new
                        {
                            ProductId = 1,
                            ColorId = 4
                        },
                        new
                        {
                            ProductId = 1,
                            ColorId = 5
                        },
                        new
                        {
                            ProductId = 2,
                            ColorId = 1
                        },
                        new
                        {
                            ProductId = 2,
                            ColorId = 2
                        },
                        new
                        {
                            ProductId = 2,
                            ColorId = 3
                        },
                        new
                        {
                            ProductId = 2,
                            ColorId = 4
                        },
                        new
                        {
                            ProductId = 2,
                            ColorId = 5
                        },
                        new
                        {
                            ProductId = 3,
                            ColorId = 1
                        },
                        new
                        {
                            ProductId = 3,
                            ColorId = 2
                        },
                        new
                        {
                            ProductId = 3,
                            ColorId = 3
                        },
                        new
                        {
                            ProductId = 3,
                            ColorId = 4
                        },
                        new
                        {
                            ProductId = 3,
                            ColorId = 5
                        },
                        new
                        {
                            ProductId = 4,
                            ColorId = 1
                        },
                        new
                        {
                            ProductId = 4,
                            ColorId = 2
                        },
                        new
                        {
                            ProductId = 4,
                            ColorId = 3
                        },
                        new
                        {
                            ProductId = 4,
                            ColorId = 4
                        },
                        new
                        {
                            ProductId = 4,
                            ColorId = 5
                        },
                        new
                        {
                            ProductId = 5,
                            ColorId = 1
                        },
                        new
                        {
                            ProductId = 5,
                            ColorId = 2
                        },
                        new
                        {
                            ProductId = 5,
                            ColorId = 3
                        },
                        new
                        {
                            ProductId = 5,
                            ColorId = 4
                        },
                        new
                        {
                            ProductId = 5,
                            ColorId = 5
                        },
                        new
                        {
                            ProductId = 7,
                            ColorId = 1
                        },
                        new
                        {
                            ProductId = 7,
                            ColorId = 2
                        },
                        new
                        {
                            ProductId = 7,
                            ColorId = 3
                        },
                        new
                        {
                            ProductId = 7,
                            ColorId = 4
                        },
                        new
                        {
                            ProductId = 7,
                            ColorId = 5
                        },
                        new
                        {
                            ProductId = 8,
                            ColorId = 1
                        },
                        new
                        {
                            ProductId = 8,
                            ColorId = 2
                        },
                        new
                        {
                            ProductId = 8,
                            ColorId = 3
                        },
                        new
                        {
                            ProductId = 8,
                            ColorId = 4
                        },
                        new
                        {
                            ProductId = 8,
                            ColorId = 5
                        },
                        new
                        {
                            ProductId = 9,
                            ColorId = 1
                        },
                        new
                        {
                            ProductId = 9,
                            ColorId = 2
                        },
                        new
                        {
                            ProductId = 9,
                            ColorId = 3
                        },
                        new
                        {
                            ProductId = 9,
                            ColorId = 4
                        },
                        new
                        {
                            ProductId = 9,
                            ColorId = 5
                        },
                        new
                        {
                            ProductId = 10,
                            ColorId = 1
                        },
                        new
                        {
                            ProductId = 10,
                            ColorId = 2
                        },
                        new
                        {
                            ProductId = 10,
                            ColorId = 3
                        },
                        new
                        {
                            ProductId = 10,
                            ColorId = 4
                        },
                        new
                        {
                            ProductId = 10,
                            ColorId = 5
                        },
                        new
                        {
                            ProductId = 11,
                            ColorId = 1
                        },
                        new
                        {
                            ProductId = 11,
                            ColorId = 2
                        },
                        new
                        {
                            ProductId = 11,
                            ColorId = 3
                        },
                        new
                        {
                            ProductId = 11,
                            ColorId = 4
                        },
                        new
                        {
                            ProductId = 11,
                            ColorId = 5
                        },
                        new
                        {
                            ProductId = 12,
                            ColorId = 2
                        },
                        new
                        {
                            ProductId = 12,
                            ColorId = 5
                        },
                        new
                        {
                            ProductId = 13,
                            ColorId = 1
                        },
                        new
                        {
                            ProductId = 13,
                            ColorId = 2
                        },
                        new
                        {
                            ProductId = 13,
                            ColorId = 3
                        },
                        new
                        {
                            ProductId = 13,
                            ColorId = 4
                        },
                        new
                        {
                            ProductId = 13,
                            ColorId = 5
                        },
                        new
                        {
                            ProductId = 14,
                            ColorId = 1
                        },
                        new
                        {
                            ProductId = 14,
                            ColorId = 2
                        },
                        new
                        {
                            ProductId = 14,
                            ColorId = 3
                        },
                        new
                        {
                            ProductId = 14,
                            ColorId = 4
                        },
                        new
                        {
                            ProductId = 14,
                            ColorId = 5
                        },
                        new
                        {
                            ProductId = 16,
                            ColorId = 1
                        },
                        new
                        {
                            ProductId = 16,
                            ColorId = 2
                        },
                        new
                        {
                            ProductId = 16,
                            ColorId = 3
                        },
                        new
                        {
                            ProductId = 16,
                            ColorId = 4
                        },
                        new
                        {
                            ProductId = 16,
                            ColorId = 5
                        });
                });

            modelBuilder.Entity("CozaStoreAPI.Infrastructure.Data.Models.ProductOrder", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<string>("Color")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("The color of the product at the time of the order");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasComment("The image path of the product at the time of the order");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("The price of the product at the time of the order");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasComment("The quantity of the product in the order");

                    b.Property<string>("Size")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("The size of the product at the time of the order");

                    b.HasKey("ProductId", "OrderId");

                    b.HasIndex("OrderId");

                    b.ToTable("ProductsOrders", t =>
                        {
                            t.HasComment("Many to many relation between products and orders");
                        });
                });

            modelBuilder.Entity("CozaStoreAPI.Infrastructure.Data.Models.ProductSize", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasComment("The product's id");

                    b.Property<int>("SizeId")
                        .HasColumnType("integer")
                        .HasComment("The size's id");

                    b.HasKey("ProductId", "SizeId");

                    b.HasIndex("SizeId");

                    b.ToTable("ProductsSizes", t =>
                        {
                            t.HasComment("Many to many relation between products and sizes");
                        });

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            SizeId = 1
                        },
                        new
                        {
                            ProductId = 1,
                            SizeId = 2
                        },
                        new
                        {
                            ProductId = 1,
                            SizeId = 3
                        },
                        new
                        {
                            ProductId = 1,
                            SizeId = 4
                        },
                        new
                        {
                            ProductId = 1,
                            SizeId = 5
                        },
                        new
                        {
                            ProductId = 2,
                            SizeId = 1
                        },
                        new
                        {
                            ProductId = 2,
                            SizeId = 2
                        },
                        new
                        {
                            ProductId = 2,
                            SizeId = 3
                        },
                        new
                        {
                            ProductId = 2,
                            SizeId = 4
                        },
                        new
                        {
                            ProductId = 2,
                            SizeId = 5
                        },
                        new
                        {
                            ProductId = 3,
                            SizeId = 1
                        },
                        new
                        {
                            ProductId = 3,
                            SizeId = 2
                        },
                        new
                        {
                            ProductId = 3,
                            SizeId = 3
                        },
                        new
                        {
                            ProductId = 3,
                            SizeId = 4
                        },
                        new
                        {
                            ProductId = 3,
                            SizeId = 5
                        },
                        new
                        {
                            ProductId = 4,
                            SizeId = 1
                        },
                        new
                        {
                            ProductId = 4,
                            SizeId = 2
                        },
                        new
                        {
                            ProductId = 4,
                            SizeId = 3
                        },
                        new
                        {
                            ProductId = 4,
                            SizeId = 4
                        },
                        new
                        {
                            ProductId = 4,
                            SizeId = 5
                        },
                        new
                        {
                            ProductId = 5,
                            SizeId = 1
                        },
                        new
                        {
                            ProductId = 5,
                            SizeId = 2
                        },
                        new
                        {
                            ProductId = 5,
                            SizeId = 3
                        },
                        new
                        {
                            ProductId = 5,
                            SizeId = 4
                        },
                        new
                        {
                            ProductId = 5,
                            SizeId = 5
                        },
                        new
                        {
                            ProductId = 7,
                            SizeId = 1
                        },
                        new
                        {
                            ProductId = 7,
                            SizeId = 2
                        },
                        new
                        {
                            ProductId = 7,
                            SizeId = 3
                        },
                        new
                        {
                            ProductId = 7,
                            SizeId = 4
                        },
                        new
                        {
                            ProductId = 7,
                            SizeId = 5
                        },
                        new
                        {
                            ProductId = 8,
                            SizeId = 1
                        },
                        new
                        {
                            ProductId = 8,
                            SizeId = 2
                        },
                        new
                        {
                            ProductId = 8,
                            SizeId = 3
                        },
                        new
                        {
                            ProductId = 8,
                            SizeId = 4
                        },
                        new
                        {
                            ProductId = 8,
                            SizeId = 5
                        },
                        new
                        {
                            ProductId = 9,
                            SizeId = 6
                        },
                        new
                        {
                            ProductId = 9,
                            SizeId = 7
                        },
                        new
                        {
                            ProductId = 9,
                            SizeId = 8
                        },
                        new
                        {
                            ProductId = 9,
                            SizeId = 9
                        },
                        new
                        {
                            ProductId = 10,
                            SizeId = 1
                        },
                        new
                        {
                            ProductId = 10,
                            SizeId = 2
                        },
                        new
                        {
                            ProductId = 10,
                            SizeId = 3
                        },
                        new
                        {
                            ProductId = 10,
                            SizeId = 4
                        },
                        new
                        {
                            ProductId = 10,
                            SizeId = 5
                        },
                        new
                        {
                            ProductId = 11,
                            SizeId = 1
                        },
                        new
                        {
                            ProductId = 11,
                            SizeId = 2
                        },
                        new
                        {
                            ProductId = 11,
                            SizeId = 3
                        },
                        new
                        {
                            ProductId = 11,
                            SizeId = 4
                        },
                        new
                        {
                            ProductId = 11,
                            SizeId = 5
                        },
                        new
                        {
                            ProductId = 12,
                            SizeId = 11
                        },
                        new
                        {
                            ProductId = 12,
                            SizeId = 12
                        },
                        new
                        {
                            ProductId = 12,
                            SizeId = 13
                        },
                        new
                        {
                            ProductId = 12,
                            SizeId = 14
                        },
                        new
                        {
                            ProductId = 13,
                            SizeId = 1
                        },
                        new
                        {
                            ProductId = 13,
                            SizeId = 2
                        },
                        new
                        {
                            ProductId = 13,
                            SizeId = 3
                        },
                        new
                        {
                            ProductId = 13,
                            SizeId = 4
                        },
                        new
                        {
                            ProductId = 13,
                            SizeId = 5
                        },
                        new
                        {
                            ProductId = 14,
                            SizeId = 1
                        },
                        new
                        {
                            ProductId = 14,
                            SizeId = 2
                        },
                        new
                        {
                            ProductId = 14,
                            SizeId = 3
                        },
                        new
                        {
                            ProductId = 14,
                            SizeId = 4
                        },
                        new
                        {
                            ProductId = 14,
                            SizeId = 5
                        },
                        new
                        {
                            ProductId = 16,
                            SizeId = 1
                        },
                        new
                        {
                            ProductId = 16,
                            SizeId = 2
                        },
                        new
                        {
                            ProductId = 16,
                            SizeId = 3
                        },
                        new
                        {
                            ProductId = 16,
                            SizeId = 4
                        },
                        new
                        {
                            ProductId = 16,
                            SizeId = 5
                        });
                });

            modelBuilder.Entity("CozaStoreAPI.Infrastructure.Data.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("The review's primary key");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasComment("The author Id");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasComment("The comment of the review.");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("The date when the review was created.");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasComment("The product Id");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasComment("The rating of the review.");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("The title of the review.");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ProductId");

                    b.ToTable("Reviews", t =>
                        {
                            t.HasComment("The review of the product");
                        });
                });

            modelBuilder.Entity("CozaStoreAPI.Infrastructure.Data.Models.Size", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("The size's primary key");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("The size's name");

                    b.HasKey("Id");

                    b.ToTable("Sizes", t =>
                        {
                            t.HasComment("The size of the product");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "XS"
                        },
                        new
                        {
                            Id = 2,
                            Name = "S"
                        },
                        new
                        {
                            Id = 3,
                            Name = "M"
                        },
                        new
                        {
                            Id = 4,
                            Name = "L"
                        },
                        new
                        {
                            Id = 5,
                            Name = "XL"
                        },
                        new
                        {
                            Id = 6,
                            Name = "36"
                        },
                        new
                        {
                            Id = 7,
                            Name = "37"
                        },
                        new
                        {
                            Id = 8,
                            Name = "38"
                        },
                        new
                        {
                            Id = 9,
                            Name = "39"
                        },
                        new
                        {
                            Id = 10,
                            Name = "40"
                        },
                        new
                        {
                            Id = 11,
                            Name = "85"
                        },
                        new
                        {
                            Id = 12,
                            Name = "90"
                        },
                        new
                        {
                            Id = 13,
                            Name = "95"
                        },
                        new
                        {
                            Id = 14,
                            Name = "100"
                        });
                });

            modelBuilder.Entity("CozaStoreAPI.Infrastructure.Data.Models.StatusOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Primary key");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Name of the status");

                    b.HasKey("Id");

                    b.ToTable("StatusOrders", t =>
                        {
                            t.HasComment("Status of the order");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Неизпълнена"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Отменена"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Изпълнена"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Получена"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Върната"
                        });
                });

            modelBuilder.Entity("CozaStoreAPI.Infrastructure.Data.Models.Subscribe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Subscribes");
                });

            modelBuilder.Entity("CozaStoreAPI.Infrastructure.Data.Models.WishUser", b =>
                {
                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uuid")
                        .HasComment("The user id");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasComment("The product id");

                    b.HasKey("AppUserId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("Wishes", t =>
                        {
                            t.HasComment("This table contains the products that the user has added to his wish list");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CozaStoreAPI.Infrastructure.Data.Models.EcontOffice", b =>
                {
                    b.HasOne("CozaStoreAPI.Infrastructure.Data.Models.EcontCity", "City")
                        .WithMany("Offices")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("CozaStoreAPI.Infrastructure.Data.Models.ImageProduct", b =>
                {
                    b.HasOne("CozaStoreAPI.Infrastructure.Data.Models.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CozaStoreAPI.Infrastructure.Data.Models.ImageReview", b =>
                {
                    b.HasOne("CozaStoreAPI.Infrastructure.Data.Models.Review", "Review")
                        .WithMany("Images")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Review");
                });

            modelBuilder.Entity("CozaStoreAPI.Infrastructure.Data.Models.Order", b =>
                {
                    b.HasOne("CozaStoreAPI.Infrastructure.Data.Models.AppUser", "AppUser")
                        .WithMany("Orders")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CozaStoreAPI.Infrastructure.Data.Models.StatusOrder", "StatusOrder")
                        .WithMany("Orders")
                        .HasForeignKey("StatusOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("StatusOrder");
                });

            modelBuilder.Entity("CozaStoreAPI.Infrastructure.Data.Models.Product", b =>
                {
                    b.HasOne("CozaStoreAPI.Infrastructure.Data.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CozaStoreAPI.Infrastructure.Data.Models.ProductColor", b =>
                {
                    b.HasOne("CozaStoreAPI.Infrastructure.Data.Models.Color", "Color")
                        .WithMany("ProductsColors")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CozaStoreAPI.Infrastructure.Data.Models.Product", "Product")
                        .WithMany("Colors")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Color");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CozaStoreAPI.Infrastructure.Data.Models.ProductOrder", b =>
                {
                    b.HasOne("CozaStoreAPI.Infrastructure.Data.Models.Order", "Order")
                        .WithMany("ProductsOrders")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CozaStoreAPI.Infrastructure.Data.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CozaStoreAPI.Infrastructure.Data.Models.ProductSize", b =>
                {
                    b.HasOne("CozaStoreAPI.Infrastructure.Data.Models.Product", "Product")
                        .WithMany("Sizes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CozaStoreAPI.Infrastructure.Data.Models.Size", "Size")
                        .WithMany("ProductsSizes")
                        .HasForeignKey("SizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("CozaStoreAPI.Infrastructure.Data.Models.Review", b =>
                {
                    b.HasOne("CozaStoreAPI.Infrastructure.Data.Models.AppUser", "Author")
                        .WithMany("Reviews")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CozaStoreAPI.Infrastructure.Data.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CozaStoreAPI.Infrastructure.Data.Models.WishUser", b =>
                {
                    b.HasOne("CozaStoreAPI.Infrastructure.Data.Models.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CozaStoreAPI.Infrastructure.Data.Models.Product", "Product")
                        .WithMany("WishesUsers")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("CozaStoreAPI.Infrastructure.Data.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("CozaStoreAPI.Infrastructure.Data.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CozaStoreAPI.Infrastructure.Data.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("CozaStoreAPI.Infrastructure.Data.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CozaStoreAPI.Infrastructure.Data.Models.AppUser", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("CozaStoreAPI.Infrastructure.Data.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CozaStoreAPI.Infrastructure.Data.Models.Color", b =>
                {
                    b.Navigation("ProductsColors");
                });

            modelBuilder.Entity("CozaStoreAPI.Infrastructure.Data.Models.EcontCity", b =>
                {
                    b.Navigation("Offices");
                });

            modelBuilder.Entity("CozaStoreAPI.Infrastructure.Data.Models.Order", b =>
                {
                    b.Navigation("ProductsOrders");
                });

            modelBuilder.Entity("CozaStoreAPI.Infrastructure.Data.Models.Product", b =>
                {
                    b.Navigation("Colors");

                    b.Navigation("Images");

                    b.Navigation("Reviews");

                    b.Navigation("Sizes");

                    b.Navigation("WishesUsers");
                });

            modelBuilder.Entity("CozaStoreAPI.Infrastructure.Data.Models.Review", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("CozaStoreAPI.Infrastructure.Data.Models.Size", b =>
                {
                    b.Navigation("ProductsSizes");
                });

            modelBuilder.Entity("CozaStoreAPI.Infrastructure.Data.Models.StatusOrder", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
